// Package table is a vendored copy of charm.land/bubbles/v2/table (v2.0.0).
// Local divergences from upstream: EnsureCursorVisible(), scrollToCursor() and
// VisibleRange(), plus the revised MoveUp/MoveDown scroll logic that calls
// scrollToCursor() for minimal scrolling instead of upstream's default behavior.
// Original: MIT License, Copyright (c) 2020-2026 Charmbracelet, Inc.
package table

import (
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/key"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap KeyMap
	Help   help.Model

	// RowStyleFunc is an optional callback that returns a style override for a given row index.
	// When set and it returns non-nil for a row, that style is used instead of the default.
	// For the cursor row (isCursor=true): returning nil lets the default
	// styles.Selected apply (selection wins), while returning a non-nil style
	// overrides even the cursor highlight. See renderRow for the exact behavior.
	RowStyleFunc func(index int, isCursor bool) *lipgloss.Style

	cols   []Column
	rows   []Row
	cursor int
	focus  bool
	styles Styles

	viewport     viewport.Model
	xOffset      int
	contentWidth int
	start        int
	end          int
}

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	LineUp       key.Binding
	LineDown     key.Binding
	PageUp       key.Binding
	PageDown     key.Binding
	HalfPageUp   key.Binding
	HalfPageDown key.Binding
	GotoTop      key.Binding
	GotoBottom   key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.LineUp, km.LineDown}
}

// FullHelp implements the KeyMap interface.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.LineUp, km.LineDown, km.GotoTop, km.GotoBottom},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
	}
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		LineUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown"),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *Model) SetStyles(s Styles) {
	m.styles = s
	m.UpdateViewport()
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(opts ...Option) Model {
	m := Model{
		cursor:   0,
		viewport: viewport.New(viewport.WithHeight(20)), //nolint:mnd

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: DefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateViewport()

	return m
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.viewport.SetWidth(w)
	}
}

// WithFocused sets the focus state of the table.
func WithFocused(f bool) Option {
	return func(m *Model) {
		m.focus = f
	}
}

// WithStyles sets the table styles.
func WithStyles(s Styles) Option {
	return func(m *Model) {
		m.styles = s
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.UpdateViewport()
}

// View renders the component.
func (m Model) View() string {
	return m.headersView() + "\n" + m.viewport.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *Model) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor >= 0 {
		m.start = clamp(m.cursor-m.viewport.Height(), 0, m.cursor)
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor+m.viewport.Height(), m.cursor, len(m.rows))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// EnsureCursorVisible snaps the viewport so the cursor row is visible: it is a
// no-op when the cursor is already within the visible window, and otherwise
// CENTERS the cursor in the viewport. Use this after external changes that may
// have moved the cursor off-screen (focus changes, data/row updates).
//
// See also scrollToCursor, which performs a minimal scroll (bringing the cursor
// to the nearest edge) and is used for interactive MoveUp/MoveDown.
func (m *Model) EnsureCursorVisible() {
	m.UpdateViewport()
	cursorLine := m.cursor - m.start
	yOffset := m.viewport.YOffset()
	height := m.viewport.Height()

	// Already visible — no-op
	if cursorLine >= yOffset && cursorLine < yOffset+height {
		return
	}

	// Center the cursor in the viewport
	newOffset := max(cursorLine-height/2, 0)
	m.viewport.SetYOffset(newOffset)
}

// RowAtY maps a y-coordinate (relative to the table's top-left, 0 = header row
// when a header is shown) to the underlying row index. Returns -1 if y falls
// on the header row, above it, or past the last data row. Pure lookup — does
// not mutate any state.
//
// Header height is always 1 because View() always emits exactly one header
// line (see headersView()); the literal is used here instead of a
// lipgloss.Height round-trip for speed. If headers ever become optional or
// multi-line, recompute from headersView().
func (m *Model) RowAtY(localY int) int {
	const headerHeight = 1
	offset := localY - headerHeight
	if offset < 0 {
		return -1
	}
	// Off the bottom of the visible viewport: no row here even if m.rows
	// still has data beyond the scrolled window.
	if offset >= m.viewport.Height() {
		return -1
	}
	// The rendered window starts at m.start in the data; the viewport then
	// scrolls within that rendered slice by viewport.YOffset() lines. So the
	// data row visible at body-line `offset` is m.start + YOffset + offset.
	idx := m.start + m.viewport.YOffset() + offset
	if idx < 0 || idx >= len(m.rows) {
		return -1
	}
	return idx
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m Model) SelectedRow() Row {
	if m.cursor < 0 || m.cursor >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor]
}

// Rows returns the current rows.
func (m Model) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m Model) Columns() []Column {
	return m.cols
}

// VisibleRange reports the half-open range [start, end) of row indices that
// the viewport renders around the cursor. Valid after UpdateViewport (called
// by SetRows/SetColumns/SetCursor/Move*). The window is bounded by ~2*Height.
//
// Local divergence from upstream: exposes the internal m.start/m.end window so
// callers can do work (e.g. highlighting) limited to the rendered rows.
func (m Model) VisibleRange() (int, int) { return m.start, m.end }

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor > len(m.rows)-1 {
		m.cursor = max(0, len(m.rows)-1)
	}

	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.UpdateViewport()
}

// SetColumnsAndRows sets columns and rows in a single operation,
// calling UpdateViewport only once.
func (m *Model) SetColumnsAndRows(c []Column, r []Row) {
	m.cols = c
	m.rows = r
	if m.cursor > len(m.rows)-1 {
		m.cursor = max(0, len(m.rows)-1)
	}
	m.UpdateViewport()
}

// SetWidth sets the width of the viewport of the table.
func (m *Model) SetWidth(w int) {
	m.viewport.SetWidth(w)
	m.UpdateViewport()
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	m.UpdateViewport()
}

// SetLayout sets columns, width, and height in a single operation,
// calling UpdateViewport only once instead of three times.
func (m *Model) SetLayout(cols []Column, w, h int) {
	m.cols = cols
	m.viewport.SetWidth(w)
	m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m Model) Height() int {
	return m.viewport.Height()
}

// Width returns the viewport width of the table.
func (m Model) Width() int {
	return m.viewport.Width()
}

// SetXOffset sets the horizontal scroll offset, clamped to valid range.
func (m *Model) SetXOffset(n int) {
	maxOffset := max(0, m.contentWidth-m.viewport.Width())
	m.xOffset = clamp(n, 0, maxOffset)
	m.UpdateViewport()
}

// XOffset returns the current horizontal scroll offset.
func (m Model) XOffset() int {
	return m.xOffset
}

// SetContentWidth sets the total content width for horizontal scroll calculations.
func (m *Model) SetContentWidth(w int) {
	m.contentWidth = w
	maxOffset := max(0, m.contentWidth-m.viewport.Width())
	m.xOffset = clamp(m.xOffset, 0, maxOffset)
}

// Cursor returns the index of the selected row.
func (m Model) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *Model) SetCursor(n int) {
	m.cursor = clamp(n, 0, max(0, len(m.rows)-1))
	m.UpdateViewport()
}

// scrollToCursor adjusts the viewport so the cursor row is visible while
// scrolling the minimum amount needed. If the cursor is already within the
// visible window, the window does not move; otherwise it shifts just enough
// to bring the cursor to the nearest viewport edge. This minimal-scroll
// strategy is used for interactive MoveUp/MoveDown.
//
// See also EnsureCursorVisible, which instead centers the cursor when it is
// off-screen and is used to snap after external changes (focus/data updates).
func (m *Model) scrollToCursor() {
	height := m.viewport.Height()
	if height <= 0 {
		// A zero-height viewport has no visible window to scroll within;
		// just recompute and leave the offset alone.
		m.UpdateViewport()
		return
	}
	// First visible data row, captured before UpdateViewport recomputes m.start.
	top := m.start + m.viewport.YOffset()
	if m.cursor < top {
		top = m.cursor
	} else if m.cursor > top+height-1 {
		top = m.cursor - height + 1
	}
	m.UpdateViewport() // recomputes m.start/m.end around the new cursor
	m.viewport.SetYOffset(max(0, top-m.start))
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, max(0, len(m.rows)-1))
	m.scrollToCursor()
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, max(0, len(m.rows)-1))
	m.scrollToCursor()
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{} //nolint:prealloc
	for line := range strings.SplitSeq(value, "\n") {
		r := Row{}
		for field := range strings.SplitSeq(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m Model) headersView() string {
	s := make([]string, 0, len(m.cols))
	for _, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(col.Width).MaxWidth(col.Width).Inline(true)
		renderedCell := style.Render(col.Title)
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	line := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	if m.xOffset > 0 || m.contentWidth > m.viewport.Width() {
		vw := m.viewport.Width()
		line = ansi.Cut(line, m.xOffset, m.xOffset+vw)
		if w := ansi.StringWidth(line); w < vw {
			line += strings.Repeat(" ", vw-w)
		}
	}
	return line
}

func (m *Model) renderRow(r int) string {
	s := make([]string, 0, len(m.cols))
	for i, value := range m.rows[r] {
		// Defensive bounds guard: plugin-provided rows may contain more cells
		// than declared columns (e.g. generic runtime-discovered plugins).
		// Drop the extras rather than panicking with index out of range.
		if i >= len(m.cols) {
			break
		}
		if m.cols[i].Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(m.cols[i].Width).MaxWidth(m.cols[i].Width).Inline(true)
		renderedCell := m.styles.Cell.Render(style.Render(value))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	// Apply horizontal clipping BEFORE styling so background spans full padded width
	if m.xOffset > 0 || m.contentWidth > m.viewport.Width() {
		vw := m.viewport.Width()
		row = ansi.Cut(row, m.xOffset, m.xOffset+vw)
		if w := ansi.StringWidth(row); w < vw {
			row += strings.Repeat(" ", vw-w)
		}
	}

	// Apply selection/row style AFTER clipping so background covers padding.
	// A whole-row override (health tint / mark) applies a single foreground over
	// the entire row, so per-cell color SGRs must be removed first — otherwise an
	// inner cell color would override the tint mid-row. We strip cell styling but
	// preserve reverse-video toggles (SGR 7/27) so an active search-match highlight
	// stays visible on tinted rows; reverse video swaps fg/bg and reads correctly
	// over any tint.
	if r == m.cursor {
		if m.RowStyleFunc != nil {
			if override := m.RowStyleFunc(r, true); override != nil {
				return override.Render(stripStyleKeepReverse(row))
			}
		}
		return m.styles.Selected.Render(row)
	}

	if m.RowStyleFunc != nil {
		if override := m.RowStyleFunc(r, false); override != nil {
			return override.Render(stripStyleKeepReverse(row))
		}
	}

	return row
}

// stripStyleKeepReverse removes ANSI styling from s but preserves reverse-video
// toggles (SGR 7 "\x1b[7m" and SGR 27 "\x1b[27m"). This lets a whole-row tint
// span uniformly while keeping reverse-video search-match highlights visible.
func stripStyleKeepReverse(s string) string {
	if !strings.Contains(s, "\x1b") {
		return s
	}
	const (
		revOn  = "\x1b[7m"
		revOff = "\x1b[27m"
	)
	// Splice the reverse-video markers back into the fully-stripped text by
	// tracking their positions in visual (stripped) space.
	type marker struct {
		visualPos int
		seq       string
	}
	var markers []marker
	stripped := ansi.Strip(s)

	// vi counts non-escape BYTES of s. ansi.Strip removes only escape
	// sequences and preserves every non-escape byte in order, so vi equals the
	// byte offset of the next character into stripped — correct for multi-byte
	// UTF-8 because we never split a rune (markers land between whole sequences).
	//
	// Only CSI SGR sequences ever reach a rendered table cell here: cell colors
	// come from lipgloss (CSI SGR) and search highlights emit \x1b[7m/\x1b[27m.
	// No OSC/DCS sequences are produced, so the simple CSI-style skip below is
	// sufficient; reusing the full ansi parser would add no correctness.
	oi, vi := 0, 0
	for oi < len(s) {
		if s[oi] == '\x1b' && strings.HasPrefix(s[oi:], revOn) {
			markers = append(markers, marker{vi, revOn})
			oi += len(revOn)
			continue
		}
		if s[oi] == '\x1b' && strings.HasPrefix(s[oi:], revOff) {
			markers = append(markers, marker{vi, revOff})
			oi += len(revOff)
			continue
		}
		if s[oi] == '\x1b' {
			// Skip any other escape sequence without advancing visual position.
			oi++
			for oi < len(s) && !isANSITerminator(s[oi]) {
				oi++
			}
			if oi < len(s) {
				oi++
			}
			continue
		}
		oi++
		vi++
	}

	if len(markers) == 0 {
		return stripped
	}

	var sb strings.Builder
	sb.Grow(len(stripped) + len(markers)*len(revOff))
	last := 0
	for _, mk := range markers {
		if mk.visualPos > len(stripped) {
			mk.visualPos = len(stripped)
		}
		sb.WriteString(stripped[last:mk.visualPos])
		sb.WriteString(mk.seq)
		last = mk.visualPos
	}
	sb.WriteString(stripped[last:])
	return sb.String()
}

// isANSITerminator reports whether b is the final byte of an ANSI escape sequence.
func isANSITerminator(b byte) bool {
	return (b >= 'A' && b <= 'Z') || (b >= 'a' && b <= 'z')
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
