// Package table is a vendored copy of charm.land/bubbles/v2/table (v2.0.0)
// with the addition of EnsureCursorVisible().
// Original: MIT License, Copyright (c) 2020-2026 Charmbracelet, Inc.
package table

import (
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/key"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap KeyMap
	Help   help.Model

	// RowStyleFunc is an optional callback that returns a style override for a given row index.
	// When set, if it returns non-nil for a row, that style is used instead of the default.
	// For cursor rows (isCursor=true), it takes priority over styles.Selected.
	RowStyleFunc func(index int, isCursor bool) *lipgloss.Style

	cols   []Column
	rows   []Row
	cursor int
	focus  bool
	styles Styles

	viewport     viewport.Model
	xOffset      int
	contentWidth int
	start        int
	end          int
}

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title string
	Width int
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	LineUp       key.Binding
	LineDown     key.Binding
	PageUp       key.Binding
	PageDown     key.Binding
	HalfPageUp   key.Binding
	HalfPageDown key.Binding
	GotoTop      key.Binding
	GotoBottom   key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.LineUp, km.LineDown}
}

// FullHelp implements the KeyMap interface.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.LineUp, km.LineDown, km.GotoTop, km.GotoBottom},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
	}
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		LineUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown"),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header   lipgloss.Style
	Cell     lipgloss.Style
	Selected lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this table.
func DefaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Header:   lipgloss.NewStyle().Bold(true).Padding(0, 1),
		Cell:     lipgloss.NewStyle().Padding(0, 1),
	}
}

// SetStyles sets the table styles.
func (m *Model) SetStyles(s Styles) {
	m.styles = s
	m.UpdateViewport()
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(opts ...Option) Model {
	m := Model{
		cursor:   0,
		viewport: viewport.New(viewport.WithHeight(20)), //nolint:mnd

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
		styles: DefaultStyles(),
	}

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateViewport()

	return m
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.viewport.SetWidth(w)
	}
}

// WithFocused sets the focus state of the table.
func WithFocused(f bool) Option {
	return func(m *Model) {
		m.focus = f
	}
}

// WithStyles sets the table styles.
func WithStyles(s Styles) Option {
	return func(m *Model) {
		m.styles = s
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.UpdateViewport()
}

// View renders the component.
func (m Model) View() string {
	return m.headersView() + "\n" + m.viewport.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *Model) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor >= 0 {
		m.start = clamp(m.cursor-m.viewport.Height(), 0, m.cursor)
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor+m.viewport.Height(), m.cursor, len(m.rows))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// EnsureCursorVisible adjusts the viewport scroll offset so the cursor row
// is centered in the viewport. No-op if cursor is already in view.
func (m *Model) EnsureCursorVisible() {
	m.UpdateViewport()
	cursorLine := m.cursor - m.start
	yOffset := m.viewport.YOffset()
	height := m.viewport.Height()

	// Already visible — no-op
	if cursorLine >= yOffset && cursorLine < yOffset+height {
		return
	}

	// Center the cursor in the viewport
	newOffset := max(cursorLine-height/2, 0)
	m.viewport.SetYOffset(newOffset)
}

// RowAtY maps a y-coordinate (relative to the table's top-left, 0 = header row
// when a header is shown) to the underlying row index. Returns -1 if y falls
// on the header row, above it, or past the last data row. Pure lookup — does
// not mutate any state.
//
// Header height is always 1 because View() always emits exactly one header
// line (see headersView()); the literal is used here instead of a
// lipgloss.Height round-trip for speed. If headers ever become optional or
// multi-line, recompute from headersView().
func (m *Model) RowAtY(localY int) int {
	const headerHeight = 1
	offset := localY - headerHeight
	if offset < 0 {
		return -1
	}
	// Off the bottom of the visible viewport: no row here even if m.rows
	// still has data beyond the scrolled window.
	if offset >= m.viewport.Height() {
		return -1
	}
	// The rendered window starts at m.start in the data; the viewport then
	// scrolls within that rendered slice by viewport.YOffset() lines. So the
	// data row visible at body-line `offset` is m.start + YOffset + offset.
	idx := m.start + m.viewport.YOffset() + offset
	if idx < 0 || idx >= len(m.rows) {
		return -1
	}
	return idx
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m Model) SelectedRow() Row {
	if m.cursor < 0 || m.cursor >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor]
}

// Rows returns the current rows.
func (m Model) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m Model) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor > len(m.rows)-1 {
		m.cursor = max(0, len(m.rows)-1)
	}

	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.UpdateViewport()
}

// SetColumnsAndRows sets columns and rows in a single operation,
// calling UpdateViewport only once.
func (m *Model) SetColumnsAndRows(c []Column, r []Row) {
	m.cols = c
	m.rows = r
	if m.cursor > len(m.rows)-1 {
		m.cursor = max(0, len(m.rows)-1)
	}
	m.UpdateViewport()
}

// SetWidth sets the width of the viewport of the table.
func (m *Model) SetWidth(w int) {
	m.viewport.SetWidth(w)
	m.UpdateViewport()
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	m.UpdateViewport()
}

// SetLayout sets columns, width, and height in a single operation,
// calling UpdateViewport only once instead of three times.
func (m *Model) SetLayout(cols []Column, w, h int) {
	m.cols = cols
	m.viewport.SetWidth(w)
	m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m Model) Height() int {
	return m.viewport.Height()
}

// Width returns the viewport width of the table.
func (m Model) Width() int {
	return m.viewport.Width()
}

// SetXOffset sets the horizontal scroll offset, clamped to valid range.
func (m *Model) SetXOffset(n int) {
	maxOffset := max(0, m.contentWidth-m.viewport.Width())
	m.xOffset = clamp(n, 0, maxOffset)
	m.UpdateViewport()
}

// XOffset returns the current horizontal scroll offset.
func (m Model) XOffset() int {
	return m.xOffset
}

// SetContentWidth sets the total content width for horizontal scroll calculations.
func (m *Model) SetContentWidth(w int) {
	m.contentWidth = w
	maxOffset := max(0, m.contentWidth-m.viewport.Width())
	m.xOffset = clamp(m.xOffset, 0, maxOffset)
}

// Cursor returns the index of the selected row.
func (m Model) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *Model) SetCursor(n int) {
	m.cursor = clamp(n, 0, max(0, len(m.rows)-1))
	m.UpdateViewport()
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, max(0, len(m.rows)-1))

	offset := m.viewport.YOffset()
	switch {
	case m.start == 0:
		offset = clamp(offset, 0, m.cursor)
	case m.start < m.viewport.Height():
		offset = clamp(clamp(offset+n, 0, m.cursor), 0, m.viewport.Height())
	case offset >= 1:
		offset = clamp(offset+n, 1, m.viewport.Height())
	}
	m.viewport.SetYOffset(offset)
	m.UpdateViewport()
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, max(0, len(m.rows)-1))
	m.UpdateViewport()

	offset := m.viewport.YOffset()
	switch {
	case m.end == len(m.rows) && offset > 0:
		offset = clamp(offset-n, 1, m.viewport.Height())
	case m.cursor > (m.end-m.start)/2 && offset > 0:
		offset = clamp(offset-n, 1, m.cursor)
	case offset > 1:
	case m.cursor > offset+m.viewport.Height()-1:
		offset = clamp(offset+1, 0, 1)
	}
	m.viewport.SetYOffset(offset)
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{} //nolint:prealloc
	for line := range strings.SplitSeq(value, "\n") {
		r := Row{}
		for field := range strings.SplitSeq(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m Model) headersView() string {
	s := make([]string, 0, len(m.cols))
	for _, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(col.Width).MaxWidth(col.Width).Inline(true)
		renderedCell := style.Render(col.Title)
		s = append(s, m.styles.Header.Render(renderedCell))
	}
	line := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	if m.xOffset > 0 || m.contentWidth > m.viewport.Width() {
		vw := m.viewport.Width()
		line = ansi.Cut(line, m.xOffset, m.xOffset+vw)
		if w := ansi.StringWidth(line); w < vw {
			line += strings.Repeat(" ", vw-w)
		}
	}
	return line
}

func (m *Model) renderRow(r int) string {
	s := make([]string, 0, len(m.cols))
	for i, value := range m.rows[r] {
		// Defensive bounds guard: plugin-provided rows may contain more cells
		// than declared columns (e.g. generic runtime-discovered plugins).
		// Drop the extras rather than panicking with index out of range.
		if i >= len(m.cols) {
			break
		}
		if m.cols[i].Width <= 0 {
			continue
		}
		style := lipgloss.NewStyle().Width(m.cols[i].Width).MaxWidth(m.cols[i].Width).Inline(true)
		renderedCell := m.styles.Cell.Render(style.Render(value))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	// Apply horizontal clipping BEFORE styling so background spans full padded width
	if m.xOffset > 0 || m.contentWidth > m.viewport.Width() {
		vw := m.viewport.Width()
		row = ansi.Cut(row, m.xOffset, m.xOffset+vw)
		if w := ansi.StringWidth(row); w < vw {
			row += strings.Repeat(" ", vw-w)
		}
	}

	// Apply selection/row style AFTER clipping so background covers padding
	if r == m.cursor {
		if m.RowStyleFunc != nil {
			if override := m.RowStyleFunc(r, true); override != nil {
				return override.Render(row)
			}
		}
		return m.styles.Selected.Render(row)
	}

	if m.RowStyleFunc != nil {
		if override := m.RowStyleFunc(r, false); override != nil {
			return override.Render(row)
		}
	}

	return row
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
